import { describe, expect, it } from "vitest";
import { normalizeOpenRouterCatalog, OpenRouterCatalogError } from "@/lib/openrouter/catalog";
import { ACCESS_LEVEL_MAX_TIER, accessForLevel, validateModelSelection } from "@/lib/model-policy/access";
import { applyTerraFixModelPolicy } from "@/lib/model-policy/catalog";
import { toAgentModelRegistry } from "@/lib/model-policy/registry";
import { isModelPolicyReady } from "@/lib/model-policy/readiness";
import type { CatalogModel } from "@/lib/model-policy/types";
import { REPOSITORY_CONFIG_DEFAULTS } from "@/lib/repository-config/constants";

const now = new Date("2026-08-23T00:00:00.000Z");

function external(overrides: Record<string, unknown> = {}) {
  return { id: "openrouter/free", canonical_slug: "openrouter/free", name: "OpenRouter Free", description: "Free router", context_length: 128_000, pricing: { prompt: "0", completion: "0" }, supported_parameters: ["response_format"], ...overrides };
}

function catalog(overrides: Partial<CatalogModel> = {}): CatalogModel {
  return { provider: "openrouter", modelId: "openrouter/free", canonicalSlug: "openrouter/free", displayName: "OpenRouter Free", description: null, tier: "FREE", enabled: true, recommended: true, available: true, isFree: true, supportsStructuredOutput: false, supportsJsonFallback: true, contextLength: 128_000, pricingPromptPerMillion: "0", pricingOutputPerMillion: "0", upstreamProvider: "openrouter", priority: 10, policyVersion: "terrafix_model_policy_v1", lastSeenAt: now, lastSyncedAt: now, ...overrides };
}

describe("Phase 9 model policy", () => {
  it("maps account access levels centrally", () => {
    expect(ACCESS_LEVEL_MAX_TIER).toEqual({ FREE: "FREE", PRO: "BALANCED", ADVANCED: "PREMIUM" });
  });

  it("normalizes authoritative free, paid, missing-price, and malformed entries", () => {
    const result = normalizeOpenRouterCatalog({ data: [
      external(),
      external({ id: "openai/paid", name: "Paid", pricing: { prompt: "0.0000015", completion: "0.000004" }, supported_parameters: ["structured_outputs"] }),
      external({ id: "openai/unknown", name: "Unknown", pricing: null }),
      { id: "bad model id", name: "Ignored" },
    ] });
    expect(result).toMatchObject({ received: 4, rejected: 1 });
    expect(result.models[0]).toMatchObject({ isFree: true, pricingPromptPerMillion: "0", pricingOutputPerMillion: "0", supportsJsonFallback: true });
    expect(result.models[1]).toMatchObject({ isFree: false, pricingPromptPerMillion: "1.5", pricingOutputPerMillion: "4", supportsStructuredOutput: true });
    expect(result.models[2]).toMatchObject({ isFree: null, pricingPromptPerMillion: null, pricingOutputPerMillion: null });
  });

  it("rejects duplicate external model identifiers", () => {
    expect(() => normalizeOpenRouterCatalog({ data: [external(), external()] })).toThrow(OpenRouterCatalogError);
  });

  it("keeps unclassified and non-authoritatively-free models disabled", () => {
    const unknown = normalizeOpenRouterCatalog({ data: [external({ id: "vendor/new-model", name: "New" })] }).models[0];
    const notConfirmedFree = normalizeOpenRouterCatalog({ data: [external({ pricing: null })] }).models[0];
    expect(applyTerraFixModelPolicy(unknown, now)).toMatchObject({ tier: null, enabled: false });
    expect(applyTerraFixModelPolicy(notConfirmedFree, now)).toMatchObject({ tier: "FREE", enabled: false, isFree: null });
  });

  it("rejects a crafted higher tier and unauthorized fixed model", () => {
    const free = accessForLevel("FREE");
    expect(validateModelSelection({ modelRouting: "auto", maxModelTier: "premium", fixedModelId: null }, free)).toContain("not available");
    expect(validateModelSelection({ modelRouting: "fixed", maxModelTier: "free", fixedModelId: "openai/premium" }, free, catalog({ modelId: "openai/premium", tier: "PREMIUM", isFree: false }))).toContain("not available");
  });

  it("generates the exact compatible agent v1 registry and excludes unavailable models", () => {
    expect(toAgentModelRegistry([catalog(), catalog({ modelId: "gone/model", available: false })], "FREE")).toEqual({ models: [{ provider: "openrouter", model_id: "openrouter/free", tier: "free", priority: 10, enabled: true, supports_structured_output: false, supports_json_fallback: true, supports_tools: false, max_context_tokens: 128_000, notes: "Generated by terrafix_model_policy_v1." }] });
  });

  it("marks unavailable fixed policies for attention while eligible auto stays ready", () => {
    const access = accessForLevel("FREE");
    expect(isModelPolicyReady(REPOSITORY_CONFIG_DEFAULTS, [catalog()], access)).toBe(true);
    expect(isModelPolicyReady({ ...REPOSITORY_CONFIG_DEFAULTS, modelRouting: "fixed", fixedModelId: "gone/model", model: "gone/model" }, [catalog()], access)).toBe(false);
  });
});
