ALTER TABLE "AgentRun"
ADD COLUMN "llmCalls" JSONB,
ADD COLUMN "cachedInputTokens" INTEGER,
ADD COLUMN "reasoningTokens" INTEGER,
ADD COLUMN "totalTokens" INTEGER,
ADD COLUMN "llmCallCount" INTEGER,
ADD COLUMN "llmCostUsd" DECIMAL(20,10),
ADD COLUMN "costComplete" BOOLEAN,
ADD COLUMN "tokenCountsComplete" BOOLEAN,
ADD COLUMN "llmLatencyMs" INTEGER,
ADD COLUMN "llmProvider" TEXT,
ADD COLUMN "requestedModel" TEXT,
ADD COLUMN "reportedModel" TEXT,
ADD COLUMN "upstreamProvider" TEXT,
ADD COLUMN "routingMode" TEXT,
ADD COLUMN "maxModelTier" TEXT,
ADD COLUMN "initialModel" TEXT,
ADD COLUMN "finalModel" TEXT,
ADD COLUMN "initialModelTier" TEXT,
ADD COLUMN "finalModelTier" TEXT,
ADD COLUMN "modelEscalated" BOOLEAN,
ADD COLUMN "initialContextLevel" TEXT,
ADD COLUMN "finalContextLevel" TEXT,
ADD COLUMN "contextEscalated" BOOLEAN,
ADD COLUMN "contextEscalationReason" TEXT,
ADD COLUMN "schemaRetrieved" BOOLEAN,
ADD COLUMN "schemaAvoided" BOOLEAN,
ADD COLUMN "sourceCharactersAvailable" INTEGER,
ADD COLUMN "sourceCharactersSelected" INTEGER,
ADD COLUMN "sourceReductionRatio" DOUBLE PRECISION,
ADD COLUMN "schemaCharactersAvailable" INTEGER,
ADD COLUMN "schemaCharactersSelected" INTEGER,
ADD COLUMN "schemaReductionRatio" DOUBLE PRECISION,
ADD COLUMN "failureMemoryStatus" TEXT,
ADD COLUMN "failureMemoryReused" BOOLEAN,
ADD COLUMN "freshVerificationPassed" BOOLEAN,
ADD COLUMN "resolutionSource" TEXT,
ADD COLUMN "candidateSource" TEXT,
ADD COLUMN "llmCallsAvoided" INTEGER,
ADD COLUMN "historicalTokensAvoided" INTEGER,
ADD COLUMN "historicalCostAvoidedUsd" DECIMAL(20,10),
ADD COLUMN "agentVersion" TEXT;

CREATE INDEX "AgentRun_modelProvider_createdAt_idx" ON "AgentRun"("modelProvider", "createdAt");
CREATE INDEX "AgentRun_llmProvider_createdAt_idx" ON "AgentRun"("llmProvider", "createdAt");
CREATE INDEX "AgentRun_reportedModel_createdAt_idx" ON "AgentRun"("reportedModel", "createdAt");
