import type { Metadata } from "next";
import Link from "next/link";
import { BrainCircuit, CircleDollarSign, DatabaseZap, Gauge, Sparkles, Zap } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { MetricCard } from "@/components/metric-card";
import { ModelTierBadge } from "@/components/model-tier-badge";
import { PageIntro } from "@/components/page-intro";
import { UsagePeriodSwitcher } from "@/components/usage-period-switcher";
import { UsageCompletenessWarning } from "@/components/usage-completeness-warning";
import { Card, CardContent } from "@/components/ui/card";
import { formatCompactTokens, formatPercent, formatUsd } from "@/lib/analytics/format";
import { getUsageAnalyticsForUser, parseUsagePeriod } from "@/lib/analytics/usage";
import { requireAuthenticatedUser } from "@/lib/auth/session";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "AI Usage", description: "TerraFix AI usage, provider-reported cost, and optimization observability." };

export default async function UsagePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [user, params] = await Promise.all([requireAuthenticatedUser(), searchParams]);
  const period = parseUsagePeriod(single(params.period));
  const usage = await getUsageAnalyticsForUser(user.id, period);
  const completeCosts = usage.completedRunCount > 0 && usage.costCompleteRuns === usage.completedRunCount;
  const completeTokens = usage.completedRunCount > 0 && usage.tokenCompleteRuns === usage.completedRunCount;

  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><PageIntro eyebrow="Observability" title="AI usage & optimization" description="Provider-reported cost, model routing, context reduction, and verified-memory reuse across repositories you can access." /><UsagePeriodSwitcher period={period} path="/usage" /></div>
    {!usage.runCount ? <EmptyState icon={BrainCircuit} title="No usage data yet" description="TerraFix will show token usage, model cost, and optimization metrics after your first diagnosis." /> : <>
      <section aria-labelledby="usage-summary-heading"><h2 id="usage-summary-heading" className="sr-only">Usage summary</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Total tokens" value={formatCompactTokens(usage.totalTokens)} description={`Based on ${usage.tokenCompleteRuns} of ${usage.completedRunCount} completed diagnoses`} icon={Sparkles} /><MetricCard title="AI spend" value={formatUsd(usage.aiSpendUsd)} description={`Reported by ${usage.costCompleteRuns} of ${usage.completedRunCount} completed diagnoses`} icon={CircleDollarSign} /><MetricCard title="Average cost / run" value={usage.averageCostPerRunUsd === null ? "Not enough data" : formatUsd(usage.averageCostPerRunUsd)} description="Shown only when selected cost data is complete" icon={Gauge} /><MetricCard title="Cost / verified fix" value={usage.costPerVerifiedFixUsd === null ? "Not enough complete cost data" : formatUsd(usage.costPerVerifiedFixUsd)} description="Complete reported cost divided by verified fixes" icon={Zap} /></div></section>
      {usage.completedRunCount > 0 && !completeCosts ? <UsageCompletenessWarning>Cost totals include {usage.costCompleteRuns} of {usage.completedRunCount} completed diagnoses with complete provider-reported cost. Missing cost is never treated as zero.</UsageCompletenessWarning> : null}
      {usage.completedRunCount > 0 && !completeTokens ? <UsageCompletenessWarning>Token totals are based on {usage.tokenCompleteRuns} of {usage.completedRunCount} completed diagnoses. Historical runs with missing token telemetry are excluded.</UsageCompletenessWarning> : null}
      <section aria-labelledby="optimization-summary-heading"><h2 id="optimization-summary-heading" className="mb-3 text-sm font-semibold">Optimization signals</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Model calls" value={usage.modelCalls.toLocaleString()} description={usage.averageModelCallsPerRun === null ? "Average not reported" : `${usage.averageModelCallsPerRun.toFixed(2)} average calls / reported run`} icon={BrainCircuit} /><MetricCard title="Zero-LLM runs" value={usage.zeroLlmRuns.toLocaleString()} description={`${formatPercent(usage.zeroLlmResolutionRate)} of runs reporting resolution source`} icon={Zap} /><MetricCard title="Schema avoidance" value={formatPercent(usage.schemaAvoidanceRate)} description={`${usage.schemaAvoidanceReportedRuns} runs reported this telemetry`} icon={Gauge} /><MetricCard title="Memory reuse" value={formatPercent(usage.memoryReuseRate)} description={`${usage.memoryReuseReportedRuns} runs reported this telemetry`} icon={DatabaseZap} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><SignalCard label="Context escalation rate" value={formatPercent(usage.contextEscalationRate)} population={usage.contextEscalationReportedRuns} /><SignalCard label="Model escalation rate" value={formatPercent(usage.modelEscalationRate)} population={usage.modelEscalationReportedRuns} /></div></section>
      <section aria-labelledby="repository-breakdown-heading"><div className="mb-3"><h2 id="repository-breakdown-heading" className="text-sm font-semibold">By repository</h2><p className="mt-1 text-xs text-muted-foreground">Cost per verified fix is withheld when a repository has incomplete selected cost data.</p></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[780px] text-left text-xs"><thead><tr className="border-b bg-secondary/30 text-muted-foreground"><TableHead>Repository</TableHead><TableHead numeric>Runs</TableHead><TableHead numeric>Tokens</TableHead><TableHead numeric>Cost</TableHead><TableHead numeric>Verified fixes</TableHead><TableHead numeric>Cost / verified fix</TableHead></tr></thead><tbody>{usage.repositoryBreakdown.map((row) => <tr key={row.repositoryId} className="border-b last:border-0"><td className="px-4 py-3.5"><Link href={`/repositories/${row.repositoryId}`} className="font-medium hover:underline">{row.repository}</Link></td><TableCell>{row.runs.toLocaleString()}</TableCell><TableCell>{formatCompactTokens(row.tokens)}</TableCell><TableCell>{formatUsd(row.costUsd)}</TableCell><TableCell>{row.verifiedFixes.toLocaleString()}</TableCell><TableCell>{row.costPerVerifiedFixUsd === null ? "Not enough data" : formatUsd(row.costPerVerifiedFixUsd)}</TableCell></tr>)}</tbody></table></CardContent></Card></section>
      <section aria-labelledby="model-breakdown-heading"><div className="mb-3"><h2 id="model-breakdown-heading" className="text-sm font-semibold">By model</h2><p className="mt-1 text-xs text-muted-foreground">Verified-fix counts provide operational context; they do not establish model quality by themselves.</p></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b bg-secondary/30 text-muted-foreground"><TableHead>Model</TableHead><TableHead>Tier</TableHead><TableHead numeric>Calls</TableHead><TableHead numeric>Input tokens</TableHead><TableHead numeric>Output tokens</TableHead><TableHead numeric>Cost</TableHead><TableHead numeric>Verified fixes</TableHead></tr></thead><tbody>{usage.modelBreakdown.map((row) => <tr key={row.model} className="border-b last:border-0"><td className="max-w-72 px-4 py-3.5 font-mono"><span className="block truncate" title={row.model}>{row.model}</span></td><td className="px-4 py-3.5"><ModelTierBadge tier={row.tier} /></td><TableCell>{row.calls.toLocaleString()}</TableCell><TableCell>{row.inputTokens.toLocaleString()}</TableCell><TableCell>{row.outputTokens.toLocaleString()}</TableCell><TableCell>{formatUsd(row.costUsd)}</TableCell><TableCell>{row.verifiedFixes.toLocaleString()}</TableCell></tr>)}</tbody></table></CardContent></Card></section>
    </>}
  </div>;
}

function SignalCard({ label, value, population }: { label: string; value: string; population: number }) { return <Card><CardContent className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-medium">{label}</p><p className="mt-1 text-[11px] text-muted-foreground">Across {population} runs reporting this telemetry</p></div><span className="font-mono text-lg font-semibold">{value}</span></CardContent></Card>; }
function TableHead({ children, numeric = false }: { children: React.ReactNode; numeric?: boolean }) { return <th scope="col" className={`px-4 py-3 font-medium ${numeric ? "text-right" : ""}`}>{children}</th>; }
function TableCell({ children }: { children: React.ReactNode }) { return <td className="whitespace-nowrap px-4 py-3.5 text-right font-mono text-muted-foreground">{children}</td>; }
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
