import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Activity, BrainCircuit, CircleDollarSign, GitCompareArrows, Sparkles, Target, Zap } from "lucide-react";
import { AnalyticsKpiCard } from "@/components/analytics/analytics-kpi-card";
import { DataCompleteness } from "@/components/analytics/data-completeness";
import { OptimizationTrendChart, SpendTrendChart, TokenTrendChart, VerificationTrendChart } from "@/components/analytics/usage-trend-charts";
import { EmptyState } from "@/components/empty-state";
import { ModelTierBadge } from "@/components/model-tier-badge";
import { PageIntro } from "@/components/page-intro";
import { UsagePeriodSwitcher } from "@/components/usage-period-switcher";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { compareMetric } from "@/lib/analytics/comparison";
import { formatCompactTokens, formatPercent, formatUsd } from "@/lib/analytics/format";
import { getUsageAnalytics } from "@/lib/analytics/trends";
import { parseUsagePeriod, type RepositoryUsageBreakdown } from "@/lib/analytics/usage";
import { requireAuthenticatedUser } from "@/lib/auth/session";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Usage Analytics", description: "TerraFix AI usage trends, verification outcomes, and optimization analytics." };

export default async function UsagePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [user, params] = await Promise.all([requireAuthenticatedUser(), searchParams]);
  const period = parseUsagePeriod(single(params.period));
  const repositoryId = single(params.repository) || undefined;
  const model = single(params.model) || undefined;
  const sort = validSort(single(params.sort));
  const analytics = await getUsageAnalytics({ userId: user.id, period, repositoryId, model });
  if (!analytics) notFound();
  const usage = analytics.current;
  const previous = analytics.previous;
  const query = { repository: repositoryId, model, sort };
  const tokenComparable = completeTokens(usage) && previous !== null && completeTokens(previous);
  const costComparable = completeCosts(usage) && previous !== null && completeCosts(previous);

  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><PageIntro eyebrow="Analytics" title="Usage analytics" description="Trends and comparisons for provider-reported cost, verification, context efficiency, model routing, and verified-memory reuse." /><UsagePeriodSwitcher period={period} path="/usage" query={query} /></div>
    <form className="grid gap-3 rounded-lg border bg-card p-4 sm:grid-cols-[1fr_1fr_auto]" aria-label="Usage analytics filters"><input type="hidden" name="period" value={period} /><label className="space-y-1.5 text-xs text-muted-foreground">Repository<Select name="repository" defaultValue={repositoryId ?? ""}><option value="">All repositories</option>{analytics.repositories.map((repo) => <option key={repo.id} value={repo.id}>{repo.fullName}</option>)}</Select></label><label className="space-y-1.5 text-xs text-muted-foreground">Model<Select name="model" defaultValue={model ?? ""}><option value="">All models</option>{analytics.models.map((item) => <option key={item} value={item}>{item}</option>)}</Select></label><button className="self-end rounded-md border bg-background px-4 py-2 text-xs font-medium hover:bg-secondary" type="submit">Apply filters</button></form>

    {!usage.runCount ? <EmptyState icon={BrainCircuit} title="No TerraFix runs in this period" description="Choose another period or repository. Missing production data is never replaced with demo analytics." /> : <>
      <section aria-labelledby="primary-kpis"><h2 id="primary-kpis" className="sr-only">Usage overview</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <AnalyticsKpiCard title="Total runs" value={usage.runCount.toLocaleString()} description="All authorized TerraFix runs in the selected period." icon={Activity} comparison={compareMetric(usage.runCount, previous?.runCount ?? null)} />
        <AnalyticsKpiCard title="Total tokens" value={usage.tokenCompleteRuns ? formatCompactTokens(usage.totalTokens) : "Not reported"} description={`Based on ${usage.tokenCompleteRuns} of ${usage.completedRunCount} completed diagnoses.`} icon={Sparkles} comparison={tokenComparable ? compareMetric(usage.totalTokens, previous!.totalTokens) : null} />
        <AnalyticsKpiCard title="AI spend" value={usage.costCompleteRuns ? formatUsd(usage.aiSpendUsd) : "Not reported"} description="Provider-reported cost; missing values are excluded, never zero-filled." icon={CircleDollarSign} comparison={costComparable ? compareMetric(Number(usage.aiSpendUsd), Number(previous!.aiSpendUsd)) : null} />
        <AnalyticsKpiCard title="Fully verified" value={usage.verifiedFixes.toLocaleString()} description={`${formatPercent(usage.verificationRate)} of completed diagnosable runs passed provider-aware plan.`} icon={Target} comparison={compareMetric(usage.verifiedFixes, previous?.verifiedFixes ?? null)} />
        <AnalyticsKpiCard title="Locally validated" value={usage.locallyValidated.toLocaleString()} description="Local Terraform checks passed; provider-aware plan was not run." icon={GitCompareArrows} comparison={compareMetric(usage.locallyValidated, previous?.locallyValidated ?? null)} />
        <AnalyticsKpiCard title="Average cost / reporting run" value={usage.averageCostPerRunUsd === null ? "Not reported" : formatUsd(usage.averageCostPerRunUsd)} description={`${usage.costCompleteRuns} of ${usage.completedRunCount} completed diagnoses reported complete cost.`} icon={CircleDollarSign} comparison={costComparable ? compareMetric(nullableNumber(usage.averageCostPerRunUsd), nullableNumber(previous!.averageCostPerRunUsd)) : null} />
        <AnalyticsKpiCard title="Cost / verified fix" value={usage.costPerVerifiedFixUsd === null ? "Unavailable" : formatUsd(usage.costPerVerifiedFixUsd)} description={costPerVerifiedFixDescription(usage)} icon={Zap} comparison={costComparable ? compareMetric(nullableNumber(usage.costPerVerifiedFixUsd), nullableNumber(previous!.costPerVerifiedFixUsd)) : null} />
        <AnalyticsKpiCard title="Model calls" value={usage.modelCalls.toLocaleString()} description={usage.averageModelCallsPerRun === null ? "Call telemetry not reported." : `${usage.averageModelCallsPerRun.toFixed(2)} average calls per reporting run.`} icon={BrainCircuit} comparison={compareMetric(usage.modelCalls, previous?.modelCalls ?? null)} />
      </div></section>

      <DataCompleteness tokens={usage.tokenCompleteRuns} costs={usage.costCompleteRuns} total={usage.completedRunCount} />
      <section className="grid gap-4 xl:grid-cols-2" aria-label="Daily usage trends"><TokenTrendChart data={analytics.daily} /><SpendTrendChart data={analytics.daily} /><VerificationTrendChart data={analytics.daily} /></section>

      <section aria-labelledby="optimization-heading" className="space-y-4"><div><h2 id="optimization-heading" className="text-base font-semibold">Optimization effectiveness</h2><p className="mt-1 text-xs text-muted-foreground">Rates use only runs where the relevant v1 telemetry is known.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Signal title="Schema avoidance" value={formatPercent(usage.schemaAvoidanceRate)} reported={usage.schemaAvoidanceReportedRuns} href="/runs?schemaAvoided=true" /><Signal title="Context escalation" value={formatPercent(usage.contextEscalationRate)} reported={usage.contextEscalationReportedRuns} href="/runs?contextEscalated=true" /><Signal title="Model escalation" value={formatPercent(usage.modelEscalationRate)} reported={usage.modelEscalationReportedRuns} href="/runs?modelEscalated=true" /><Signal title="Memory reuse" value={formatPercent(usage.memoryReuseRate)} reported={usage.memoryReuseReportedRuns} href="/runs?memoryReused=true" /><Signal title="Zero-LLM resolution" value={formatPercent(usage.zeroLlmResolutionRate)} reported={usage.zeroLlmRuns} href="/runs?zeroLlm=true" /></div><div className="grid gap-4 xl:grid-cols-2"><OptimizationTrendChart data={analytics.daily} kind="context" /><OptimizationTrendChart data={analytics.daily} kind="reuse" /></div></section>

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" aria-label="Reduction, routing, and memory analytics"><ReductionCard title="Terraform source reduction" stats={analytics.sourceReduction} /><ReductionCard title="Provider-schema reduction" stats={analytics.schemaReduction} /><TierCard initial={analytics.initialTierDistribution} final={analytics.finalTierDistribution} escalation={usage.modelEscalationRate} /><MemoryCard stats={analytics.memory} /></section>
      {analytics.historicalSavingsReportingRuns ? <Card><CardHeader><CardTitle className="text-sm">Historical comparison</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-3"><Metric label="Reporting runs" value={String(analytics.historicalSavingsReportingRuns)} /><Metric label="Historical tokens avoided" value={formatCompactTokens(analytics.historicalTokensAvoided)} /><Metric label="Historical cost avoided" value={formatUsd(analytics.historicalCostAvoidedUsd)} /><p className="sm:col-span-3 text-xs text-muted-foreground">Authoritative historical comparisons are not a guarantee of future savings.</p></CardContent></Card> : null}
      <RepositoryTable rows={sortRepositories(usage.repositoryBreakdown, sort)} period={period} repositoryId={repositoryId} model={model} sort={sort} />
      <ModelTable rows={usage.modelBreakdown} />
    </>}
    <p className="text-[11px] text-muted-foreground">Daily buckets use UTC so server and browser views remain consistent. All-time views omit previous-period comparisons.</p>
  </div>;
}

function Signal({ title, value, reported, href }: { title: string; value: string; reported: number; href: string }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{title}</p><p className="mt-2 font-mono text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{reported} reporting run{reported === 1 ? "" : "s"}</p><Link href={href} className="mt-3 inline-block text-[11px] font-medium text-primary hover:underline">View runs</Link></CardContent></Card>; }
function ReductionCard({ title, stats }: { title: string; stats: { mean: number | null; median: number | null; reportedRuns: number } }) { return <Card><CardHeader><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Metric label="Mean" value={formatPercent(stats.mean)} /><Metric label="Median" value={formatPercent(stats.median)} /><p className="col-span-2 text-[10px] text-muted-foreground">Calculated across {stats.reportedRuns} eligible run{stats.reportedRuns === 1 ? "" : "s"}; never from daily averages.</p></CardContent></Card>; }
function TierCard({ initial, final, escalation }: { initial: Array<{ tier: string; runs: number; rate: number }>; final: Array<{ tier: string; runs: number; rate: number }>; escalation: number | null }) { return <Card><CardHeader><CardTitle className="text-sm">Model routing</CardTitle></CardHeader><CardContent className="space-y-3"><Metric label="Model escalation" value={formatPercent(escalation)} /><Metric label="Higher-tier avoidance" value={escalation === null ? "Not available" : formatPercent(1 - escalation)} /><Distribution label="Initial tiers" values={initial} /><Distribution label="Final tiers" values={final} /><p className="text-[10px] text-muted-foreground">Avoidance means a reporting run completed without model escalation. Tier is cost/access policy, not quality.</p></CardContent></Card>; }
function MemoryCard({ stats }: { stats: { reusedRuns: number; staleHits: number; freshVerifyPassed: number; freshVerifyReported: number; zeroLlmRuns: number } }) { return <Card><CardHeader><CardTitle className="text-sm">Verified Failure Memory</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Metric label="Reused" value={String(stats.reusedRuns)} /><Metric label="Zero-LLM" value={String(stats.zeroLlmRuns)} /><Metric label="Stale hits" value={String(stats.staleHits)} /><Metric label="Fresh verify passed" value={stats.freshVerifyReported ? `${stats.freshVerifyPassed} / ${stats.freshVerifyReported}` : "Not available"} /><p className="col-span-2 text-[10px] text-muted-foreground">A reused candidate is always verified again against the current repository state.</p></CardContent></Card>; }
function Distribution({ label, values }: { label: string; values: Array<{ tier: string; rate: number }> }) { return <div><p className="mb-1 text-[10px] text-muted-foreground">{label}</p>{values.length ? <div className="flex flex-wrap gap-1.5">{values.map((value) => <span key={value.tier} className="rounded border px-2 py-1 text-[10px]">{value.tier} {formatPercent(value.rate, 0)}</span>)}</div> : <p className="text-xs">Not available</p>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-medium">{value}</p></div>; }

function RepositoryTable({ rows, period, repositoryId, model, sort }: { rows: RepositoryUsageBreakdown[]; period: string; repositoryId?: string; model?: string; sort: Sort }) { return <section aria-labelledby="repositories-heading"><div className="mb-3"><h2 id="repositories-heading" className="text-base font-semibold">Repository comparison</h2><p className="mt-1 text-xs text-muted-foreground">Authorized repositories only. Sort by runs, tokens, cost, or verification rate.</p></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b bg-secondary/30 text-muted-foreground"><Head>Repository</Head>{(["runs", "tokens", "cost", "verification"] as Sort[]).map((key) => <Head key={key} numeric><Link href={usageHref({ period, repository: repositoryId, model, sort: key })} aria-current={sort === key ? "page" : undefined} className="hover:text-foreground">{key === "verification" ? "Verification rate" : title(key)}{sort === key ? " ↓" : ""}</Link></Head>)}<Head numeric>Verified</Head><Head numeric>Avg cost / reporting run</Head><Head numeric>Memory reuse</Head></tr></thead><tbody>{rows.map((row) => <tr key={row.repositoryId} className="border-b last:border-0"><td className="px-4 py-3"><Link href={`/repositories/${row.repositoryId}`} className="font-medium hover:underline">{row.repository}</Link><br /><Link href={`/runs?repository=${row.repositoryId}`} className="text-[10px] text-primary hover:underline">View runs</Link></td><Cell>{row.runs.toLocaleString()}</Cell><Cell>{row.tokenCompleteRuns ? formatCompactTokens(row.tokens) : "Not reported"}</Cell><Cell>{row.costCompleteRuns ? formatUsd(row.costUsd) : "Not reported"}</Cell><Cell>{formatPercent(row.verificationRate)}</Cell><Cell>{row.verifiedFixes.toLocaleString()}</Cell><Cell>{row.costCompleteRuns ? formatUsd(Number(row.costUsd) / row.costCompleteRuns) : "Not reported"}</Cell><Cell>{formatPercent(row.memoryReuseRate)}</Cell></tr>)}</tbody></table></CardContent></Card></section>; }
function ModelTable({ rows }: { rows: Array<{ model: string; tier: string | null; calls: number; runs: number; inputTokens: number; outputTokens: number; costUsd: string; tokenCompleteRuns: number; costCompleteRuns: number; verifiedFixes: number }> }) { return <section aria-labelledby="models-heading"><div className="mb-3"><h2 id="models-heading" className="text-base font-semibold">Model comparison</h2><p className="mt-1 text-xs text-muted-foreground">Grouped by actual reported model, then requested model when no actual identity was reported. Verified outcomes are context, not a quality score.</p></div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[820px] text-left text-xs"><thead><tr className="border-b bg-secondary/30 text-muted-foreground"><Head>Model</Head><Head>Tier</Head><Head numeric>Calls</Head><Head numeric>Runs</Head><Head numeric>Input tokens</Head><Head numeric>Output tokens</Head><Head numeric>Cost</Head><Head numeric>Verified outcomes</Head></tr></thead><tbody>{rows.map((row) => <tr key={row.model} className="border-b last:border-0"><td className="max-w-[280px] truncate px-4 py-3 font-mono"><Link href={`/runs?model=${encodeURIComponent(row.model)}`} className="hover:underline">{row.model}</Link></td><td className="px-4 py-3">{row.tier ? <ModelTierBadge tier={row.tier} /> : "Not reported"}</td><Cell>{row.calls.toLocaleString()}</Cell><Cell>{row.runs.toLocaleString()}</Cell><Cell>{row.tokenCompleteRuns ? formatCompactTokens(row.inputTokens) : "Not reported"}</Cell><Cell>{row.tokenCompleteRuns ? formatCompactTokens(row.outputTokens) : "Not reported"}</Cell><Cell>{row.costCompleteRuns ? formatUsd(row.costUsd) : "Not reported"}</Cell><Cell>{row.verifiedFixes.toLocaleString()}</Cell></tr>)}</tbody></table></CardContent></Card></section>; }
function Head({ children, numeric }: { children: React.ReactNode; numeric?: boolean }) { return <th className={`px-4 py-3 font-medium ${numeric ? "text-right" : ""}`}>{children}</th>; }
function Cell({ children }: { children: React.ReactNode }) { return <td className="px-4 py-3 text-right font-mono">{children}</td>; }
type Sort = "runs" | "tokens" | "cost" | "verification";
function validSort(value: string): Sort { return value === "tokens" || value === "cost" || value === "verification" ? value : "runs"; }
function sortRepositories(rows: RepositoryUsageBreakdown[], sort: Sort) { return [...rows].sort((a, b) => sort === "tokens" ? b.tokens - a.tokens : sort === "cost" ? Number(b.costUsd) - Number(a.costUsd) : sort === "verification" ? (b.verificationRate ?? -1) - (a.verificationRate ?? -1) : b.runs - a.runs); }
function completeTokens(value: { completedRunCount: number; tokenCompleteRuns: number }) { return value.completedRunCount > 0 && value.tokenCompleteRuns === value.completedRunCount; }
function completeCosts(value: { completedRunCount: number; costCompleteRuns: number }) { return value.completedRunCount > 0 && value.costCompleteRuns === value.completedRunCount; }
function nullableNumber(value: string | null) { return value === null ? null : Number(value); }
function costPerVerifiedFixDescription(usage: { completedRunCount: number; costCompleteRuns: number; verifiedFixes: number }) { const missing = usage.completedRunCount - usage.costCompleteRuns; if (missing > 0) return `${missing} completed ${missing === 1 ? "diagnosis lacks" : "diagnoses lack"} cost telemetry.`; if (!usage.verifiedFixes) return "No fully verified fixes in the selected period."; return "Complete diagnosis cost divided by fully verified fixes."; }
function usageHref(values: Record<string, string | undefined>) { const query = new URLSearchParams(Object.entries(values).filter((entry): entry is [string, string] => Boolean(entry[1]))); return `/usage?${query}`; }
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function title(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
