import type { ModelTier } from "@prisma/client";
import type { AgentModelRegistryEntry, CatalogModel } from "./types";

const rank: Record<ModelTier, number> = { FREE: 0, ECONOMY: 1, BALANCED: 2, PREMIUM: 3 };

export function toAgentModelRegistry(models: CatalogModel[], maximumTier: ModelTier) {
  const entries: AgentModelRegistryEntry[] = models
    .filter((model) => model.enabled && model.available && model.tier && rank[model.tier] <= rank[maximumTier] && (model.supportsStructuredOutput || model.supportsJsonFallback))
    .map((model) => ({
      provider: "openrouter" as const, model_id: model.modelId, tier: model.tier!.toLowerCase() as Lowercase<ModelTier>, priority: model.priority,
      enabled: true, supports_structured_output: model.supportsStructuredOutput, supports_json_fallback: model.supportsJsonFallback,
      supports_tools: false, max_context_tokens: model.contextLength, notes: `Generated by ${model.policyVersion}.`,
    }))
    .sort((a, b) => rank[a.tier.toUpperCase() as ModelTier] - rank[b.tier.toUpperCase() as ModelTier] || a.priority - b.priority || a.model_id.localeCompare(b.model_id));
  return { models: entries };
}
