"use client";

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCompactTokens, formatPercent, formatUsd } from "@/lib/analytics/format";
import type { DailyUsagePoint } from "@/lib/analytics/trends";

const grid = "var(--border)";
const foreground = "var(--foreground)";
const muted = "var(--muted-foreground)";
const primary = "var(--primary)";

export function TokenTrendChart({ data, compact = false }: { data: DailyUsagePoint[]; compact?: boolean }) {
  const reported = data.some((point) => point.totalTokens !== null);
  return <ChartCard title={compact ? "Token usage, last 30 days" : "Token usage"} description="Daily total tokens from reporting diagnoses; missing telemetry remains a gap." empty={!reported} compact={compact}>
    <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 8, left: compact ? -25 : -10, bottom: 0 }}><CartesianGrid stroke={grid} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis tickFormatter={(value) => formatCompactTokens(value)} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} width={52} /><Tooltip content={<TokenTooltip />} /><Area connectNulls={false} dataKey="totalTokens" name="Total tokens" stroke={primary} fill={primary} fillOpacity={0.12} strokeWidth={2} dot={data.length <= 7 ? { r: 3 } : false} activeDot={{ r: 4 }} /></AreaChart></ResponsiveContainer>
  </ChartCard>;
}

export function SpendTrendChart({ data }: { data: DailyUsagePoint[] }) {
  const chartData = data.map((point) => ({ ...point, cost: point.aiCostUsd === null ? null : Number(point.aiCostUsd) }));
  return <ChartCard title="AI spend" description="Daily provider-reported model cost. Free days remain explicit zero; unreported days are gaps." empty={!data.some((point) => point.aiCostUsd !== null)}><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 8, right: 8, left: -10, bottom: 0 }}><CartesianGrid stroke={grid} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis tickFormatter={(value) => formatUsd(value)} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} width={60} /><Tooltip content={<SpendTooltip />} /><Bar dataKey="cost" name="AI spend" fill={primary} radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>;
}

export function VerificationTrendChart({ data }: { data: DailyUsagePoint[] }) {
  const chartData = data.map((point) => ({ ...point, rate: point.verificationRate === null ? null : point.verificationRate * 100 }));
  return <ChartCard title="Full verification trend" description="Provider-aware plan passes divided by completed diagnosable runs; local validation remains separate and infrastructure failures are excluded." empty={!data.some((point) => point.verificationRate !== null)}><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, left: -10, bottom: 0 }}><CartesianGrid stroke={grid} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} width={42} /><Tooltip content={<VerificationTooltip />} /><Line connectNulls={false} dataKey="rate" name="Full verification rate" stroke={primary} strokeWidth={2} dot={data.length <= 7 ? { r: 3 } : false} activeDot={{ r: 4 }} /></LineChart></ResponsiveContainer></ChartCard>;
}

export function OptimizationTrendChart({ data, kind }: { data: DailyUsagePoint[]; kind: "context" | "reuse" }) {
  const chartData = data.map((point) => kind === "context" ? { ...point, primary: percent(point.schemaAvoidedRuns, point.schemaAvoidanceEligibleRuns), secondary: percent(point.contextEscalatedRuns, point.contextEscalationEligibleRuns) } : { ...point, primary: percent(point.memoryReusedRuns, point.memoryEligibleRuns), secondary: percent(point.zeroLlmRuns, point.resolutionSourceReportingRuns) });
  const labels = kind === "context" ? ["Schema avoidance", "Context escalation"] : ["Memory reuse", "Zero-LLM resolution"];
  return <ChartCard title={kind === "context" ? "Context efficiency" : "Reuse efficiency"} description={kind === "context" ? "Two distinct progressive-context signals, using only eligible reporting runs." : "Verified Failure Memory reuse and verified-memory resolutions requiring zero model calls."} empty={!chartData.some((point) => point.primary !== null || point.secondary !== null)}><div className="mb-2 flex gap-4 text-[11px] text-muted-foreground"><span><i className="mr-1.5 inline-block size-2 rounded-full bg-primary" />{labels[0]}</span><span><i className="mr-1.5 inline-block size-2 rounded-full bg-foreground" />{labels[1]}</span></div><div className="h-[210px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, left: -10, bottom: 0 }}><CartesianGrid stroke={grid} strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tick={{ fill: muted, fontSize: 10 }} axisLine={false} tickLine={false} width={42} /><Tooltip content={<OptimizationTooltip labels={labels} />} /><Line connectNulls={false} dataKey="primary" name={labels[0]} stroke={primary} strokeWidth={2} dot={false} /><Line connectNulls={false} dataKey="secondary" name={labels[1]} stroke={foreground} strokeDasharray="5 4" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></ChartCard>;
}

function ChartCard({ title, description, empty, compact, children }: { title: string; description: string; empty: boolean; compact?: boolean; children: React.ReactNode }) { return <Card><CardHeader className="pb-2"><CardTitle className="text-sm">{title}</CardTitle><p className="text-xs text-muted-foreground">{description}</p></CardHeader><CardContent className={compact ? "h-[180px]" : "h-[280px]"}>{empty ? <div className="flex h-full items-center justify-center rounded-lg border border-dashed text-center text-xs text-muted-foreground">No reported telemetry in this period.</div> : children}</CardContent></Card>; }
function TooltipShell({ children }: { children: React.ReactNode }) { return <div className="rounded-md border bg-popover p-3 text-xs text-popover-foreground shadow-md">{children}</div>; }
type ChartTooltipProps = { active?: boolean; payload?: ReadonlyArray<{ payload?: unknown }>; label?: string | number };
function TokenTooltip({ active, payload, label }: ChartTooltipProps) { if (!active || !payload?.[0]?.payload) return null; const p = payload[0].payload as DailyUsagePoint; return <TooltipShell><strong>{label} UTC</strong><Rows rows={[["Input", formatCompactTokens(p.inputTokens)], ["Cached input", formatCompactTokens(p.cachedInputTokens)], ["Output", formatCompactTokens(p.outputTokens)], ["Total", formatCompactTokens(p.totalTokens)], ["Reporting", `${p.tokenReportingRuns} / ${p.completedRuns} diagnoses`]]} /></TooltipShell>; }
function SpendTooltip({ active, payload, label }: ChartTooltipProps) { if (!active || !payload?.[0]?.payload) return null; const p = payload[0].payload as DailyUsagePoint & { cost: number | null }; return <TooltipShell><strong>{label} UTC</strong><Rows rows={[["Cost", p.cost === 0 ? "Free ($0.000000)" : formatUsd(p.cost)], ["Reporting", `${p.costReportingRuns} / ${p.completedRuns} diagnoses`]]} /></TooltipShell>; }
function VerificationTooltip({ active, payload, label }: ChartTooltipProps) { if (!active || !payload?.[0]?.payload) return null; const p = payload[0].payload as DailyUsagePoint; return <TooltipShell><strong>{label} UTC</strong><Rows rows={[["Verified", String(p.verifiedRuns)], ["Diagnosable", String(p.completedRuns)], ["Rate", formatPercent(p.verificationRate)]]} /></TooltipShell>; }
function OptimizationTooltip({ active, payload, label, labels }: ChartTooltipProps & { labels: string[] }) { if (!active || !payload?.[0]?.payload) return null; const p = payload[0].payload as { primary: number | null; secondary: number | null }; return <TooltipShell><strong>{label} UTC</strong><Rows rows={[[labels[0], p.primary === null ? "Not available" : `${p.primary.toFixed(1)}%`], [labels[1], p.secondary === null ? "Not available" : `${p.secondary.toFixed(1)}%`]]} /></TooltipShell>; }
function Rows({ rows }: { rows: string[][] }) { return <dl className="mt-2 grid grid-cols-[auto_auto] gap-x-5 gap-y-1">{rows.flatMap(([label, value]) => [<dt key={`${label}-l`} className="text-muted-foreground">{label}</dt>, <dd key={`${label}-v`} className="text-right font-mono">{value}</dd>])}</dl>; }
function shortDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function percent(numerator: number, denominator: number) { return denominator ? (numerator / denominator) * 100 : null; }
